### PR TITLE
Try to catch errors on load and alert user

### PR DESCRIPTION
**Pull request by mark-fathom**

### CODE REVIEW

**Comment by kayserifserif** [comment]
I uploaded a small file with some characters deleted and dates misformatted, and didn't get a visible error alert.

[ma_sars_cov_2 copy.fasta.zip](https://github.com/user-attachments/files/17170215/ma_sars_cov_2.copy.fasta.zip)

**Comment by mark-fathom** [comment]
Thanks for that test. Will look into it.

**Comment by kayserifserif** [comment]
Cool, thanks!

I uploaded my bogus file and got the warning. Then, without reloading the page, I tried to upload a correctly formatted file, but it didn't go. The file otherwise works correctly on a fresh reload.

**Comment by mark-fathom** [comment]
Huh, just trying this out, and I _was_ able to load a new file in the same session.

**Comment by kayserifserif** [comment]
Oh, you're right! Maybe I was too hasty. We could probably remove the "Parsing…" loader at the bottom when it fails, to help clarify that. But it works!

**Review by kayserifserif — APPROVED** [review]

**Pull request merged**
